// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for proto-based Spec and Status fields

package v1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto for the IstioInstallation.Spec
func (in *IstioInstallationSpec) DeepCopyInto(out *IstioInstallationSpec) {
	p := proto.Clone(in).(*IstioInstallationSpec)
	*out = *p
}

// DeepCopyInto for the IstioInstallation.Status
func (in *IstioInstallationStatus) DeepCopyInto(out *IstioInstallationStatus) {
	p := proto.Clone(in).(*IstioInstallationStatus)
	*out = *p
}
